apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      initContainers:
          - name: init-mydb
            image: busybox
            command: ['sh','-c', 'until nslookup db01.default.svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
          - name: init-memcached
            image: busybox
            command: ['sh','-c', 'until nslookup mc01.default.svc.cluster.local; do echo waiting for mc01; sleep 2; done;']
      containers:
      - name: app01
        image: jadonharsh/vprofile:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: app01
spec:
  type: LoadBalancer
  selector:
    app: app01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080