name: "Build & Code Test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Initial-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Printing Events Data
        run: echo '${{ toJson(github.event) }}'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.11.0

      - name: Maven Build & Test
        uses: mvn install
