# Name of the GitHub Actions workflow
name: "Deploy to CI Staging"

# Trigger events for the workflow
on:
  # Allow manual triggering of the workflow
  workflow_dispatch:
    inputs:
      PR_number:
        description: "Pull Request Number"
        required: true

############ Define the jobs for the workflow ############
jobs:
  create:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform/staging
    steps:
      - uses: actions/checkout@v3

      - name: Verify Pull Request Number
        uses: actions/github-script@v5
        id: verify_pr_number
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const response = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: ${{ github.event.inputs.PR_number }}
            });

            // Check if the pull request is open
            if (response.data.number !== ${{ github.event.inputs.PR_number }}) {
                throw new Error('Pull request is not open or number is not valid!');
            } else {
                console.log("PR ref: " + response.data.head.ref);
                return response.data.head.ref;
            }

      - name: terraform init
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
