# Name of the GitHub Actions workflow
name: "Destroy Staging Server"

# Trigger events for the workflow
on:
  pull_request:
    types:
      - closed
    paths:
      - 'app/**'
  workflow_dispatch:

############ Define the jobs for the workflow ############
jobs:
  Destroying-Staging:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Get PR details
        run: |
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
          echo "Merged By: ${{ github.event.pull_request.merged_by.login }}"
          echo "Merged at: ${{ github.event.pull_request.merged_at }}"
          echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Head Branch: ${{ github.event.pull_request.head.ref }}"
          echo "URL: ${{ github.event.pull_request.html_url }}"

      - name: terraform env setup
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        working-directory: terraform/staging
        run: terraform init

      - name: Terraform Destroy
        id: destroy
        working-directory: terraform/staging
        run: terraform destroy -var instance_name="${{ github.event.pull_request.number }}" --auto-approve
